version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - client
    ports:
      - 7800:7800

  api:
    build: api
    image: api
    restart: "no"
    volumes:
      - ./api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - .env

  client:
    build: client
    image: client
    restart: "no"
    volumes:
      - ./client/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - api

  database:
    container_name: database-server-dab-p1-994dc928-5d5d-4dfd-a0ad-fc4c0f4c10c2
    image: postgres:14.1
    restart: "no"
    env_file:
      - .env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - .env
