INSERT INTO courses (course_code, course_name, course_description)
VALUES
  ('MS-C1081', 'Abstract Algebra', 'Groups, group homomorphisms and isomorphisms, rings, ideals, integral domains, ring homomorphisms and isomorphisms, polynomials, fields.'),
  ('MS-E2145', 'Combinatorial Optimization D', 'In this course, the student will learn the fundamentals of combinatorial optimization theory and practice and also how these can be applied to real-world optimization problems. Topics addressed in the course include but are not limited to networking optimization, complexity theory, polyhedral theory, exact methods and approximation algorithms. After the course, the student can analyse the main characteristics of an optimization problem, build models of such problems using standard techniques and choose appropriate solution techniques.'),
  ('CS-E5520', 'Advanced Computer Graphics D', 'Contents may vary by year, but always form a deeper dive into the theory, algorithms, and their practical implementation of a particular subfield of computer graphics. In the past few years, the topic has been was physically based rendering, both its theory and numerical methods for generating realistic pictures.'),
  ('ELEC-A7100', 'Basic Course in C programming', 'Learn the basics of C programming language'),
  ('CS-A1130', 'Applications of Computing', 'Through practical exercises, the course introduces the processing and visualization of research data using various programming, domain-spesific, and mark up languages ​​and software such as Python, SQL, MATLAB, Simulink, and HTML5. The goal is to know how to organize information logically and formulate computational problems in such a way that it is possible to solve them using the methods typically used in Computer Science and to process, present and analyze information at different levels of abstraction such as models and simulations.'),
  ('CS-E4370', 'Applied Cryptography D', 'This is an intermediate-level course on cryptography, with focus on public-key, application-oriented cryptographic primitives. It covers definitions and constructions of core and advanced public-key primitives, and their applications in privacy-preserving systems.'),
  ('CS-E4800', 'Artificial Intelligence D', 'State-space search algorithms. Automated reasoning in the propositional logic and the predicate logic. Applications in knowledge representation and natural language processing. Probabilistic reasoning. Decision-making under uncertainty. Adaptation and learning in decision-making. Adversarial decision-making in games and game theory.'),
  ('MUO-E8017', 'Eco-auditing D', 'This workshop type of intensive course aims to familiarise the students with principles of auditing and assessing the ecological impacts of a product, material or system. During the course the students will learn to use different tools, including dedicated computer software, to aid their design process in material selection and product-system development.'),
  ('CS-C3100', 'Computer Graphics', 'Content: Geometric modelling, visual simulation, shading and lighting, ray tracing, the real-time graphics pipeline, mathematical foundations of computer graphics.'),
  ('CS-E4930', 'Software Processes and Projects D', 'Software processes. Software project planning and management. Project organization. Different project types (bespoke, software product and distributed projects). Communication and global software development.');
